POST http://localhost:3000/register/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A

###
GET http://localhost:3000/user/following/

###
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A


###
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A

###
GET http://localhost:3000/tweets/:tweetId/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A

###
GET http://localhost:3000/tweets/:tweetId/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A

###
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A

###
GET http://localhost:3000/user/tweets/

###
POST http://localhost:3000/user/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A


{
   "tweet": "The Mornings..."
}

###
DELETE http://localhost:3000/tweets/15/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.fdwNVUetdYr0I54_u5lo4ubNDDOGgy2ubUS4H794-3A
